---
env: ""
name: ""

provider: aws
prefix: kt
tf_state_bucket_region: eu-central-1
public_trusted_access_cidrs: [
  '80.94.55.80/32', # home lab
]

# ip plan
ip_addressing_plan:
  kt-dev-eks-1:
    vpc_cidr: '10.240.64.0/21'
