---
name: eks-1
cluster_version: 1.28

cluster_logs:
#  - api
#  - audit
  - authenticator
#  - controllerManager
#  - scheduler
cloudwatch_log_group_retention_in_days: 60

cluster_admin_user: arn:aws:iam::400528358945:user/terraform-admin

aws_account_admin_user:
  - arn:aws:iam::400528358945:user/terraform-admin

argocd_config:
  argocd_fqdn: argocd.jamf.fun
  helm_secrets_version: 4.2.2
  sops_version: 3.9.4
  kubectl_version: 1.28.0
  argocd_helmchart_versions: 9.4.0
  inital_app_target_revision: main

cluster_external_dns_domain_filter:
  - jamf.fun
